services:
  db:
    image: postgres:16
    container_name: controle-temperatura-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: controle_temperatura
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: controle-temperatura-backend-prod
    restart: unless-stopped
    environment:
      API_PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: controle_temperatura
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: controle-temperatura-frontend-prod
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data_prod:
